"""
Enumerations used throughout the AegisAI framework.

Enums provide strongly typed values instead of relying on string
literals, improving readability, type safety, and maintainability.
"""

from __future__ import annotations

from enum import Enum


class StrEnum(str, Enum):
    """
    Base class for string enumerations.

    Enum members behave like strings while retaining all Enum
    functionality.
    """

    def __str__(self) -> str:
        return self.value


class RiskLevel(StrEnum):
    """
    Risk level assigned to a prediction.
    """

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class Recommendation(StrEnum):
    """
    Recommendation generated by the trust engine.
    """

    AUTO_APPROVE = "Auto Approve"
    HUMAN_REVIEW = "Requires Human Review"
    REJECT = "Reject Prediction"


class ModelType(StrEnum):
    """
    Supported AI model families.
    """

    SKLEARN = "scikit-learn"
    PYTORCH = "pytorch"
    TENSORFLOW = "tensorflow"
    XGBOOST = "xgboost"
    CATBOOST = "catboost"
    LIGHTGBM = "lightgbm"
    HUGGINGFACE = "huggingface"
    OLLAMA = "ollama"
    OPENAI = "openai"


class PredictionStatus(StrEnum):
    """
    Status of the prediction pipeline.
    """

    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    WARNING = "WARNING"


class SafetyStatus(StrEnum):
    """
    Overall safety evaluation.
    """

    PASSED = "PASSED"
    FAILED = "FAILED"


class WrapperCapability(StrEnum):
    """
    Capabilities that a wrapper may implement.

    These are used internally to determine whether a model
    supports optional functionality such as probabilities.
    """

    PREDICT = "predict"
    PREDICT_PROBA = "predict_proba"
    DECISION_FUNCTION = "decision_function"
    EMBEDDINGS = "embeddings"


class ReportFormat(StrEnum):
    """
    Supported report export formats.
    """

    JSON = "json"
    HTML = "html"
    PDF = "pdf"