"""
Report models for the AegisAI framework.

Every prediction generated by AegisAI returns a PredictionReport,
which provides a structured and validated representation of the
prediction and all associated reliability metrics.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from .enums import Recommendation, RiskLevel


class SafetyReport(BaseModel):
    """
    Safety analysis for a prediction.

    In v0.1 these values are defaults. Future versions will populate
    them using dedicated safety modules.
    """

    model_config = ConfigDict(
        frozen=False,
        validate_assignment=True,
    )

    passed: bool = True
    toxicity: bool = False
    bias: bool = False
    pii: bool = False
    prompt_injection: bool = False
    hallucination: bool = False


class PredictionReport(BaseModel):
    """
    Complete prediction report returned by AegisAI.
    """

    model_config = ConfigDict(
        validate_assignment=True,
        extra="forbid",
    )

    # ==========================================================
    # Prediction
    # ==========================================================

    prediction: Any

    # ==========================================================
    # Confidence
    # ==========================================================

    confidence: float = Field(
        ge=0.0,
        le=1.0,
    )

    calibrated_confidence: float = Field(
        ge=0.0,
        le=1.0,
    )

    uncertainty: float = Field(
        ge=0.0,
    )

    # ==========================================================
    # OOD
    # ==========================================================

    ood: bool

    ood_score: float

    # ==========================================================
    # Drift
    # ==========================================================

    drift_score: float = 0.0

    # ==========================================================
    # Safety
    # ==========================================================

    safety: SafetyReport = Field(
        default_factory=SafetyReport
    )

    # ==========================================================
    # Trust
    # ==========================================================

    trust_score: float = Field(
        ge=0.0,
        le=1.0,
    )

    risk_level: RiskLevel

    recommendation: Recommendation

    # ==========================================================
    # Metadata
    # ==========================================================

    metadata: dict[str, Any] = Field(
        default_factory=dict
    )

    # ==========================================================
    # Utility Methods
    # ==========================================================

    def to_dict(self) -> dict[str, Any]:
        """
        Convert the report into a Python dictionary.

        Returns:
            Dictionary representation of the report.
        """
        return self.model_dump()

    def to_json(self, indent: int = 4) -> str:
        """
        Convert the report into formatted JSON.

        Args:
            indent:
                Number of spaces used for indentation.

        Returns:
            JSON representation of the report.
        """
        return self.model_dump_json(indent=indent)

    def summary(self) -> str:
        """
        Return a concise human-readable summary.

        Returns:
            Summary string.
        """
        return (
            f"Prediction={self.prediction}, "
            f"Confidence={self.confidence:.3f}, "
            f"Trust={self.trust_score:.3f}, "
            f"Risk={self.risk_level.value}"
        )

    def __str__(self) -> str:
        """
        Pretty string representation.
        """
        return self.to_json()